### ISSUE TITLE
how can i use sound train?

### ISSUE THREAD

**Issue by lee-hyeon-gu** [rainy-xu/TALL4Deepfake#10]
I have read your research and it was very helpful. 
The learning of images showed good performance. 
However, when I try to learn with sound, I encounter the error:
```
img = torch.ByteTensor(torch.ByteStorage.from_buffer(pic.tobytes()))
AttributeError: 'NoneType' object has no attribute 'tobytes'
```
I placed the video's entire wav files in the dataset from kodf
How can I solve this problem?

**Comment by rainy-xu** [comment]
> I have read your research and it was very helpful. The learning of images showed good performance. However, when I try to learn with sound, I encounter the error:
> 
> ```
> img = torch.ByteTensor(torch.ByteStorage.from_buffer(pic.tobytes()))
> AttributeError: 'NoneType' object has no attribute 'tobytes'
> ```
> 
> I placed the video's entire wav files in the dataset from kodf How can I solve this problem?

Unfortunately, audio processing is a bit outside of my expertise area and I may not be able to assist you effectively with this particular issue.
