### ISSUE TITLE
Question about the reimplementation of the ViViT method in the paper

### ISSUE THREAD

**Issue by kk3lamb** [rainy-xu/TALL4Deepfake#11]
Thank you for your excellent work.I would like to ask you which variant you used in implementing ViViT, or did you do all four variants? Which one is the result in the paper? Looking forward to your reply, thanks!

**Comment by rainy-xu** [comment]
> Thank you for your excellent work.I would like to ask you which variant you used in implementing ViViT, or did you do all four variants? Which one is the result in the paper? Looking forward to your reply, thanks!

We only used the variant 2：ViViT-B/16x2 FE
