### ISSUE TITLE
Data Preparation

### ISSUE THREAD

**Issue by MetroTY** [rainy-xu/TALL4Deepfake#13]
Very excellent work, can you please provide the details of the data processing process? Is the preprocessing of the data extracting each frame of the FF++ and then putting it into the dataloader before selecting the segments?Looking forward to hearing from you.

**Comment by SparklehoodDevAdmin** [comment]
Hi @MetroTY 

Do you know what 'image_tmpl' is used for in [video_dataset_config.py](https://github.com/rainy-xu/TALL4Deepfake/blob/main/video_dataset_config.py)

**Comment by MetroTY** [comment]
> Hi @MetroTY
> 
> Do you know what 'image_tmpl' is used for in [video_dataset_config.py](https://github.com/rainy-xu/TALL4Deepfake/blob/main/video_dataset_config.py)

![image](https://github.com/user-attachments/assets/36e685f6-4638-4107-995a-9cab44c9f750)
It is used in the load_image function. It's just a load template.
