### ISSUE TITLE
Some questions about comparing results in the paper

### ISSUE THREAD

**Issue by kk3lamb** [rainy-xu/TALL4Deepfake#7]
Thank you for your excellent work！

 In the paper you mentioned that you reimplemented vivit. may I ask if you reimplemented it using model 2 from vivit? Can I ask for your understanding of how vivit doesn't perform well on the ff++ dataset, while generalising other datasets performs well?

Thanks again for your work, it helps me a lot!

**Comment by rainy-xu** [comment]
@kk3lamb 

Hi， This is an interesting discovery！

Based on our understanding of the Vivit results, it is likely that Vivit is not overfitting, which is why it achieves good performance on the cross-dataset task. Other models that perform better on FF++ may suffer from overfitting.

**Comment by kk3lamb** [comment]
@rainy-xu Thank you for your patience in replying, I would like to ask you which variant you used in implementing ViViT, or did you do all four variants? Which one is the result in the paper? Looking forward to your reply, thanks!
