### ISSUE TITLE
Data Preparation

### ISSUE THREAD

**Issue by YangYangGirl** [rainy-xu/TALL4Deepfake#8]
Thank you for your excellent work. I have been using the code you provided in [detect_from_video.py](https://github.com/rainy-xu/TALL4Deepfake/blob/main/data_preparation/detect_from_video.py) to crop faces from images. However, I've noticed that some frames are missing because the faces in them are difficult to detect. I wonder when you sample 8 clips for each video using dense sampling, how do you handle the missing frames? Thanks for your answer.

**Comment by rainy-xu** [comment]
@YangYangGirl 

Hi, we removed the frames that were preprocessed incorrectly and renamed the frames sequentially, ensuring that there were no gaps in the sequence numbers among the consecutive frames.
